const fs = require('fs');
const path = require('path');

// Base articles
const articles = [
    {
        id: 'a1',
        title: 'Authentication & Authorization trong ReactJS',
        category: 'Front-End',
        excerpt: 'Chào bạn! Nếu bạn đã là học viên khóa Pro của Rikkai Academy, chắc hẳn bạn đã biết tới Dev Mode - giúp thực hành và học tập hiệu quả hơn. Trong bài viết này, chúng ta sẽ tìm hiểu về Authentication & Authorization trong ReactJS.',
        image: './card1.png',
        publishedAt: '6 tháng trước',
        readTime: '10-15 phút đọc',
    },
    {
        id: 'a2',
        title: 'State Management với Redux Toolkit',
        category: 'Front-End',
        excerpt: 'Redux Toolkit là cách tiếp cận hiện đại để quản lý state trong ứng dụng React. Bài viết này sẽ hướng dẫn bạn cách sử dụng Redux Toolkit một cách hiệu quả.',
        image: './card1.png',
        publishedAt: '5 tháng trước',
        readTime: '12-18 phút đọc',
    },
    {
        id: 'a3',
        title: 'TypeScript Best Practices',
        category: 'Front-End',
        excerpt: 'TypeScript giúp code JavaScript của bạn an toàn và dễ bảo trì hơn. Hãy cùng khám phá các best practices khi làm việc với TypeScript trong dự án React.',
        image: './card1.png',
        publishedAt: '4 tháng trước',
        readTime: '8-12 phút đọc',
    },
    {
        id: 'a4',
        title: 'Performance Optimization trong React',
        category: 'Front-End',
        excerpt: 'Tối ưu hóa hiệu suất là một phần quan trọng trong phát triển ứng dụng React. Bài viết này sẽ giới thiệu các kỹ thuật và công cụ để cải thiện performance.',
        image: './card1.png',
        publishedAt: '3 tháng trước',
        readTime: '15-20 phút đọc',
    },
    {
        id: 'a5',
        title: 'RESTful API Design Principles',
        category: 'Back-End',
        excerpt: 'Thiết kế API RESTful đúng cách là nền tảng cho một hệ thống backend mạnh mẽ. Hãy cùng tìm hiểu các nguyên tắc và best practices khi thiết kế REST API.',
        image: './card1.png',
        publishedAt: '2 tháng trước',
        readTime: '10-15 phút đọc',
    },
    {
        id: 'a6',
        title: 'Database Indexing Strategies',
        category: 'Back-End',
        excerpt: 'Indexing là một kỹ thuật quan trọng để cải thiện hiệu suất truy vấn database. Bài viết này sẽ giải thích các chiến lược indexing phổ biến và khi nào nên sử dụng chúng.',
        image: './card1.png',
        publishedAt: '1 tháng trước',
        readTime: '12-16 phút đọc',
    },
    {
        id: 'a7',
        title: 'Microservices Architecture',
        category: 'Back-End',
        excerpt: 'Kiến trúc microservices đang trở thành xu hướng trong phát triển ứng dụng lớn. Hãy cùng tìm hiểu về các khái niệm, ưu nhược điểm và cách triển khai.',
        image: './card1.png',
        publishedAt: '3 tuần trước',
        readTime: '18-25 phút đọc',
    },
    {
        id: 'a8',
        title: 'Docker và Containerization',
        category: 'DevOps',
        excerpt: 'Docker đã cách mạng hóa cách chúng ta deploy và quản lý ứng dụng. Bài viết này sẽ hướng dẫn bạn từ cơ bản đến nâng cao về Docker và containerization.',
        image: './card1.png',
        publishedAt: '2 tuần trước',
        readTime: '14-20 phút đọc',
    },
    {
        id: 'a9',
        title: 'CI/CD với GitHub Actions',
        category: 'DevOps',
        excerpt: 'GitHub Actions giúp tự động hóa quy trình CI/CD một cách dễ dàng. Hãy cùng học cách thiết lập pipeline CI/CD cho dự án của bạn với GitHub Actions.',
        image: './card1.png',
        publishedAt: '1 tuần trước',
        readTime: '10-15 phút đọc',
    },
];

// Generate 111 more articles
const generated = Array.from({ length: 111 }, (_, i) => ({
    id: `a${i + 10}`,
    title: `Bài viết ${i + 10}: ${['Front-End', 'Back-End', 'DevOps', 'Mobile'][i % 4]}`,
    category: ['Front-End', 'Back-End', 'DevOps', 'Mobile'][i % 4],
    excerpt: 'Đây là một bài viết mẫu về các chủ đề công nghệ thông tin. Nội dung bài viết sẽ được cập nhật trong tương lai.',
    image: './card1.png',
    publishedAt: `${Math.floor(i / 4) + 1} ${['tuần', 'tháng'][Math.floor(i / 20) % 2]} trước`,
    readTime: `${10 + (i % 10)}-${15 + (i % 10)} phút đọc`,
}));

const allArticles = [...articles, ...generated];

// Courses
const courses = [
    {
        id: 'c1',
        title: 'N1 Chill Class',
        category: 'N1',
        level: 'Beginner',
        durationMinutes: 360,
        chapters: 32,
        teacher: 'Giang Sensei',
        heroImage: './card1.png',
    },
    {
        id: 'c2',
        title: 'N1 Chill Class',
        category: 'N1',
        level: 'Beginner',
        durationMinutes: 360,
        chapters: 32,
        teacher: 'Giang Sensei',
        heroImage: './card1.png',
    },
    {
        id: 'c3',
        title: 'N1 Chill Class',
        category: 'N1',
        level: 'Beginner',
        durationMinutes: 360,
        chapters: 32,
        teacher: 'Giang Sensei',
        heroImage: './card1.png',
    },
    {
        id: 'c4',
        title: 'N2 Chill Class',
        category: 'N2',
        level: 'Beginner',
        durationMinutes: 360,
        chapters: 32,
        teacher: 'Quỳnh Sensei',
        heroImage: './card1.png',
    },
    {
        id: 'c5',
        title: 'N2 Chill Class',
        category: 'N2',
        level: 'Beginner',
        durationMinutes: 360,
        chapters: 32,
        teacher: 'Quỳnh Sensei',
        heroImage: './card1.png',
    },
    {
        id: 'c6',
        title: 'N2 Chill Class',
        category: 'N2',
        level: 'Beginner',
        durationMinutes: 360,
        chapters: 32,
        teacher: 'Quỳnh Sensei',
        heroImage: './card1.png',
    },
    {
        id: 'c1',
        title: 'N1 Chill Class',
        category: 'N1',
        level: 'Beginner',
        durationMinutes: 360,
        chapters: 32,
        teacher: 'Giang Sensei',
        heroImage: './card1.png',
    },
    {
        id: 'c2',
        title: 'N1 Chill Class',
        category: 'N1',
        level: 'Beginner',
        durationMinutes: 360,
        chapters: 32,
        teacher: 'Giang Sensei',
        heroImage: './card1.png',
    },
    {
        id: 'c3',
        title: 'N1 Chill Class',
        category: 'N1',
        level: 'Beginner',
        durationMinutes: 360,
        chapters: 32,
        teacher: 'Giang Sensei',
        heroImage: './card1.png',
    },
    {
        id: 'c4',
        title: 'N2 Chill Class',
        category: 'N2',
        level: 'Beginner',
        durationMinutes: 360,
        chapters: 32,
        teacher: 'Quỳnh Sensei',
        heroImage: './card1.png',
    },
    {
        id: 'c5',
        title: 'N2 Chill Class',
        category: 'N2',
        level: 'Beginner',
        durationMinutes: 360,
        chapters: 32,
        teacher: 'Quỳnh Sensei',
        heroImage: './card1.png',
    },
    {
        id: 'c6',
        title: 'N2 Chill Class',
        category: 'N2',
        level: 'Beginner',
        durationMinutes: 360,
        chapters: 32,
        teacher: 'Quỳnh Sensei',
        heroImage: './card1.png',
    },
];

const db = {
    articles: allArticles,
    courses: courses,
};

const outputPath = path.join(__dirname, 'src', 'data', 'db.json');
fs.writeFileSync(outputPath, JSON.stringify(db, null, 2), 'utf8');
console.log(`Created db.json with ${allArticles.length} articles and ${courses.length} courses`);

